networks:
  pennypincher:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - STATS_DOMAIN=${STATS_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "nginx -g 'daemon off;'"
    depends_on:
      - app
      - stats
      - backend
    networks:
      - pennypincher

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - PUBLIC_STATS_DOMAIN=${STATS_DOMAIN}
      - PUBLIC_API_DOMAIN=${API_DOMAIN}
    depends_on:
      - backend
    networks:
      - pennypincher

  stats:
    container_name: stats
    build:
      context: ./stats
      dockerfile: Dockerfile
    expose:
      - "81"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - pennypincher

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - pennypincher
